version: '3'
services:
    rtsp-server:
        container_name: rtsp-server
        image: aler9/rtsp-simple-server
        restart: always
        environment: 
            - RTSP_PROTOCOLS=tcp
        ports:
            - 1935:1935
            - 8554:8554
            - 8888:8888
        volumes:
            - ./app/rtsp-simple-server.yml:/rtsp-simple-server.yml

    wyzecam-bridge:
        container_name: wyze-bridge
        build: ./app
        restart: always
        environment:
            - WYZE_EMAIL=
            - WYZE_PASSWORD=